# Window rules
windowrule {
    name = pavucontrol
    match:class = pavucontrol
    float = on
    size = 1200 600
}

# Key bindings
bind = , XF86TouchpadToggle, exec, ~/.config/hypr/scripts/toggle-touchpad.sh
bind = $mod SHIFT, P, exec, wl-toggle-output alsa_output.pci-0000_00_1f.3.analog-stereo bluez_output.4C_87_5D_09_58_AA.1
