// services/HyprSync.qml
// Writes a Hyprland config snippet that mirrors the shell's inset tokens,
// so tiled windows line up with the wallpaper frame. Source the generated
// file from hyprland.conf:
//
//   source = ~/.config/hypr/quickshell.conf
//
// The bar's exclusive zone already reserves the left edge, so gaps_out only
// needs to cover top/right/bottom. Hyprland's gaps_out format is "T R B L".
pragma Singleton

import QtQuick
import QtCore
import Quickshell
import Quickshell.Io
import config

QtObject {
    id: root

    readonly property string _path:
        StandardPaths.writableLocation(StandardPaths.GenericConfigLocation)
        + "/hypr/quickshell.conf"

    // Outer gap = screen edge → wallpaper frame.
    // Inner gap = wallpaper frame → tiled window (visible wallpaper ring).
    // Hyprland's gaps_out is measured from reserved-area edges, so we stack
    // inner on top of outer for top/right/bottom, and use just inner on left
    // (bar exclusion already reserves the outer portion).
    readonly property int gapOuterPx: Math.round(Appearance.inset.gapOuter)
    readonly property int gapInnerPx: Math.round(Appearance.inset.gapInner)
    readonly property int radiusPx:   Math.round(Appearance.inset.corner)

    property string _lastWritten: ""

    property var _fileView: FileView {
        path: root._path
        blockLoading: false
        printErrors: false
    }

    property var _reloadProc: Process {
        id: reloadProc
        command: ["hyprctl", "reload"]
        running: false
    }

    function _render() {
        const outer = root.gapOuterPx + root.gapInnerPx;
        const left  = root.gapInnerPx;
        const r = root.radiusPx;
        return "# Generated by Quickshell HyprSync — do not edit.\n"
             + "general {\n"
             + "    gaps_out = " + outer + ", " + outer + ", " + outer + ", " + left + "\n"
             + "}\n"
             + "decoration {\n"
             + "    rounding = " + r + "\n"
             + "}\n";
    }

    function _sync() {
        const content = _render();
        if (content === _lastWritten) return;
        _fileView.setText(content);
        _lastWritten = content;
        if (!reloadProc.running) reloadProc.running = true;
    }

    property var _debounce: Timer {
        interval: 150
        repeat: false
        onTriggered: root._sync()
    }

    onGapOuterPxChanged: _debounce.restart()
    onGapInnerPxChanged: _debounce.restart()
    onRadiusPxChanged: _debounce.restart()

    Component.onCompleted: _sync()
}
